### PR TITLE
Add create_od_vertices()

### PR DESCRIPTION
**Pull request by Jake-Moss**
Heres the crack I took at `create_od_vertices()` today, let me know what you'd like changed. Not sure if using `EPSG:4326` is correct.
If we need all vertices to be assigned a `taz_id` we could use something like
```python
        zoning = self.project.zoning
        for i, row in self.vertices.iterrows():
            if row["taz_id"] is None:
                self.vertices.at[i, "taz_id"] = zoning.get_closest_zone(shapely.from_wkt(row["coord"]))
```
however this doesn't work atm due to `get_closest_zone(...)` throwing an error due to an empty `min()` call.

### CODE REVIEW

**Comment by djfrancesco** [comment]
> Heres the crack I took at `create_od_vertices()` today, let me know what you'd like changed. Not sure if using `EPSG:4326` is correct. If we need all vertices to be assigned a `taz_id` we could use something like
> 
> ```python
>         zoning = self.project.zoning
>         for i, row in self.vertices.iterrows():
>             if row["taz_id"] is None:
>                 self.vertices.at[i, "taz_id"] = zoning.get_closest_zone(shapely.from_wkt(row["coord"]))
> ```
> 
> however this doesn't work atm due to `get_closest_zone(...)` throwing an error due to an empty `min()` call.

Well only the od vertices need to be assigned a `taz_id`. That's because the demand matrix is usually expressed between zones, while in the assignment algorithm, we need to know for each zone couple, which vertices (of od type) are the source/destination in the graph.

**Comment by Jake-Moss** [comment]
Heres the script I've been using to transfer zones and centroids to the sqlite db.
```python
#!/usr/bin/python
import os
os.environ['USE_PYGEOS'] = '0'
import rasterio  # this is real stupid, if I don't import this library then geopandas segfaults

import sqlite3
import pandas as pd
import geopandas as gpd
from aequilibrae.project import Project
from aequilibrae.transit.transit_graph_builder import SF_graph_builder

con = sqlite3.connect("/home/jake/Software/aequilibrae_performance_tests/models/public_transport.sqlite")
con.enable_load_extension(True)
con.load_extension("mod_spatialite")

project = Project()
project.new("/tmp/demo")

shp_file_path = "/home/jake/Software/aequilibrae_performance_tests/models/Lyon/zones/zones.shp"

def insert_into_db(project, shp_file_path, crs="EPSG:4326"):
    zoning = project.zoning
    zones = gpd.read_file(shp_file_path)
    zones.to_crs(crs)
    zones["centroid"] = zones.centroid
    for i, row in zones.iterrows():
        z = zoning.new(i)
        z.add_centroid(row["centroid"])
        z.geometry = row["geometry"]

    zoning.save()

    pd.read_sql("SELECT * FROM zones", con=project.connect()).to_sql("zones", con)
    pd.read_sql("SELECT * FROM nodes", con=project.connect()).to_sql("nodes", con)


insert_into_db(project, shp_file_path)
project.close()


graph = SF_graph_builder(con)
graph.create_vertices()
```

**Comment by djfrancesco** [comment]
Regarding the script used for loading the zones into sqlite, I guess that you need need to update the CRS conversion part:
```python
zones.to_crs(crs, inplace=True)
```
or
```python
zones = zones.to_crs(crs)
```
Also I think that you have two lines (`pd.read_sql`) of dead code at the end of `insert_into_db` ? Or is it usefull for the sqlite part?

**Comment by Jake-Moss** [comment]
> ```python 
> zones.to_crs(crs, inplace=True)
> ```
Yep absolutely, thanks for that catch, I've edited it above.

> Also I think that you have two lines (pd.read_sql) of dead code at the end of insert_into_db ? Or is it useful for the sqlite part?

Those are to transfer the newly created vertices and zones from the `project_database.sqlite` to `public_transport.sqlite`, I wasn't able to write directly into `public_transport.sqlite` as its doesn't appear to be a valid AequilibraE project yet. The script is really just a quick hack to create the data in the manner AequilibraE expects, then export into the `public_transport.sqlite` for us to use. Should be noted that it doesn't transfer the schema and all the triggers that AequilibraE constructs. I'll look into what is missing from `public_transport.sqlite` to make it a valid project to Friday.

**Review by djfrancesco — APPROVED** [review]

**Pull request merged**
